# Generated by Django 4.2 on 2024-12-31 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formation', '0034_rename_chapitres_section_chapitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteres', models.TextField(default='')),
                ('level', models.CharField(choices=[('Beginner', 'Débutant'), ('Intermediate', 'Intermédiaire'), ('Advanced', 'Avancé')], default='Débutant', max_length=20)),
                ('cost', models.FloatField()),
                ('dateDebutValidite', models.DateField()),
                ('dateFinValidite', models.DateField()),
                ('validityPeriod', models.IntegerField()),
                ('examFormat', models.CharField(choices=[('Online', 'En ligne'), ('In-person', 'En présentiel')], default='En ligne', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='Passed', max_length=20)),
                ('numberOfQuestions', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Formation.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('valide', models.BooleanField(default=False)),
                ('tentative', models.PositiveIntegerField(default=0)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificats.certification')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='certificats.question')),
            ],
        ),
        migrations.CreateModel(
            name='CoursUseCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_certifications', to='certificats.certification')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_courses', to='Formation.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Subscribed', 'Subscribed'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Subscribed', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificats.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponseUtilisateur', to='Formation.chapitre')),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificats.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='certificats.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
