# Generated by Django 4.2 on 2024-12-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Débutant'), ('Intermediate', 'Intermédiaire'), ('Advanced', 'Avancé')], default='Débutant', max_length=20)),
                ('cost', models.FloatField()),
                ('dateDebutValidite', models.DateField()),
                ('dateFinValidite', models.DateField()),
                ('validityPeriod', models.IntegerField()),
                ('prerequisites', models.TextField()),
                ('examFormat', models.CharField(choices=[('Online', 'En ligne'), ('In-person', 'En présentiel')], default='En ligne', max_length=100)),
                ('numberOfQuestions', models.IntegerField()),
                ('passingScore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='Passed', max_length=20)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='certification.certification')),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.institution'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Subscribed', 'Subscribed'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Subscribed', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
