# Generated by Django 4.2 on 2024-12-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0021_alter_webinarenrollment_unique_together'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursUseCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_certifications', to='certification.certification')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_courses', to='Formation.cours')),
            ],
        ),
    ]
