# Generated by Django 4.2 on 2024-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_coursusecertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='objectif',
            field=models.TextField(default=''),
        ),
    ]
