# Generated by Django 4.2 on 2024-12-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0021_alter_webinarenrollment_unique_together'),
        ('certification', '0003_certification_objectif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('chapitre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Formation.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.IntegerField()),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='certification.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='certification.question'),
        ),
    ]
