# Generated by Django 4.2 on 2024-12-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_option_question_reponseutilisateur_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponseutilisateur',
            name='utilisateur_id',
        ),
    ]
