# Generated by Django 4.2 on 2024-12-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certification', '0005_remove_reponseutilisateur_utilisateur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseutilisateur',
            name='user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
