# Generated by Django 4.2 on 2024-12-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_reponseutilisateur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='reponseUtilisateur',
            field=models.TextField(default='q11', max_length=20),
        ),
    ]
