# Generated by Django 4.2 on 2024-12-17 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formation', '0021_alter_webinarenrollment_unique_together'),
        ('certification', '0007_option_reponseutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='reponseUtilisateur',
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='date_reponse',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reponseutilisateur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reponseutilisateur',
            unique_together={('user', 'question')},
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('valide', models.BooleanField(default=False)),
                ('tentative', models.PositiveIntegerField(default=0)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
