# Generated by Django 4.2 on 2024-12-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_remove_option_reponseutilisateur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReponseUtilisateur',
        ),
    ]
