# Generated by Django 4.2 on 2024-12-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0021_alter_webinarenrollment_unique_together'),
        ('certification', '0011_remove_coursusecertification_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursusecertification',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='coursusecertification',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certifications_courses', to='Formation.cours'),
        ),
    ]
