# Generated by Django 4.2 on 2024-12-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0021_alter_webinarenrollment_unique_together'),
        ('certification', '0013_remove_reponseutilisateur_date_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseutilisateur',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reponseUtilisateur', to='Formation.chapitre'),
        ),
    ]
