# Generated by Django 4.2 on 2024-12-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0023_alter_audio_nom_audio_alter_audio_section_and_more'),
        ('certification', '0016_reponseutilisateur_chapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursusecertification',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_courses', to='Formation.cours'),
        ),
        migrations.AlterField(
            model_name='option',
            name='correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Formation.chapitre'),
        ),
        migrations.AlterField(
            model_name='reponseutilisateur',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponseUtilisateur', to='Formation.chapitre'),
        ),
    ]
