# Generated by Django 4.2.15 on 2024-10-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('nom_beneficiaire', models.CharField(max_length=500)),
                ('date_debut', models.DateField(default=datetime.date(2024, 1, 20))),
                ('date_limite', models.DateField(default=datetime.date(2024, 1, 20))),
                ('duration', models.CharField(max_length=60)),
                ('niveau', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(max_length=200)),
            ],
        ),
    ]
