# Generated by Django 4.2 on 2024-11-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0002_enterprise_file_offer_offerapplication_delete_offre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerapplication',
            name='updated_at',
        ),
    ]
