# Generated by Django 4.2 on 2024-11-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0003_remove_offerapplication_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerapplication',
            name='submitted_documents_ids',
        ),
    ]
