# Generated by Django 4.2 on 2024-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0004_remove_offerapplication_submitted_documents_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='gridfs_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='file',
            name='file_content',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='application/pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Review', 'Review')], default='Accepted', max_length=20),
        ),
    ]
