# Generated by Django 4.2 on 2024-11-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0005_remove_file_created_at_remove_file_gridfs_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.BinaryField(),
        ),
    ]
