# Generated by Django 4.2 on 2024-11-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0006_alter_file_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerapplication',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='offerapplication',
            name='offer',
        ),
    ]
