# Generated by Django 4.2 on 2024-11-18 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Offres', '0008_offerapplication_submitted_documents_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapplication',
            name='candidat_id',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
