# Generated by Django 4.2 on 2024-11-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offres', '0010_remove_offerapplication_candidat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapplication',
            name='offer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Offres.offer'),
        ),
    ]
