# Generated by Django 4.2.15 on 2024-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_domaine', models.IntegerField()),
                ('Nom_domaine', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_module', models.IntegerField()),
                ('id_domaine', models.IntegerField()),
                ('nom_module', models.TextField(max_length=800)),
            ],
        ),
    ]
