# Generated by Django 4.2.15 on 2024-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chapitre', models.IntegerField()),
                ('id_cours', models.IntegerField()),
                ('titre', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenu', models.IntegerField()),
                ('id_chapitre', models.IntegerField()),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cours', models.IntegerField()),
                ('id_module', models.IntegerField()),
                ('nom_cours', models.TextField(max_length=800)),
            ],
        ),
    ]
