# Generated by Django 4.2.15 on 2024-10-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_chapitre_contenu_cours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domaine',
            old_name='Nom_domaine',
            new_name='nom_domaine',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='id_chapitre',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='id_cours',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='id_chapitre',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='id_contenu',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='id_cours',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='id_module',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='id_domaine',
        ),
        migrations.RemoveField(
            model_name='module',
            name='id_domaine',
        ),
        migrations.RemoveField(
            model_name='module',
            name='id_module',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.cours'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='chapitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre'),
        ),
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.domaine'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='titre',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom_cours',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom_module',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
