# Generated by Django 4.2.15 on 2024-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0003_rename_nom_domaine_domaine_nom_domaine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
