# Generated by Django 4.2.15 on 2024-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0005_contenu_sous_tire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenu',
            name='sous_tire',
        ),
        migrations.AddField(
            model_name='contenu',
            name='sous_titre',
            field=models.CharField(default='', max_length=800),
        ),
    ]
