# Generated by Django 4.2 on 2024-11-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0006_remove_contenu_sous_tire_contenu_sous_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('speaker', models.CharField(max_length=200)),
                ('speakerPicture_url', models.URLField(blank=True, null=True)),
                ('endDateTime', models.DateTimeField()),
                ('registrationDeadline', models.DateTimeField(blank=True, null=True)),
                ('webinarUrl', models.URLField(blank=True, null=True)),
                ('maxParticipants', models.IntegerField()),
                ('isPaid', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('FuturAllies', 'FuturAllies'), ('Café des allies', 'Café des allies')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('hasAcceptedTerms', models.BooleanField(default=False)),
                ('paymentStatus', models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('free', 'Free')], max_length=10, null=True)),
                ('paymentMethod', models.CharField(blank=True, choices=[('creditCard', 'Credit Card'), ('orangeMoney', 'Orange Money'), ('moovMoney', 'Moov Money'), ('sankMoney', 'Sank Money')], max_length=15, null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('webinarId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Formation.webinar')),
            ],
        ),
    ]
