# Generated by Django 4.2 on 2024-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0009_remove_webinar_user_webinarenrollment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='speakerPicture_url',
        ),
        migrations.AddField(
            model_name='webinar',
            name='duree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='startDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
