# Generated by Django 4.2 on 2024-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0012_webinar_webinarenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='registrationDeadline',
            field=models.DateTimeField(),
        ),
    ]
