# Generated by Django 4.2 on 2024-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0013_alter_webinar_registrationdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='format',
            field=models.CharField(choices=[('FuturAllies', 'Gratuit'), ('Café des allies', 'Payant')], default='Payant', max_length=20),
        ),
    ]
