# Generated by Django 4.2 on 2024-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0014_webinar_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='startDateTime',
            field=models.CharField(default='10 Octobre 2024', max_length=200),
        ),
    ]
