# Generated by Django 4.2 on 2024-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0016_alter_webinar_registrationdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='registrationDeadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='startDateTime',
            field=models.DateTimeField(),
        ),
    ]
