# Generated by Django 4.2 on 2024-11-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formation', '0017_alter_webinar_registrationdeadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarenrollment',
            name='fullName',
        ),
        migrations.AddField(
            model_name='webinarenrollment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
