# Generated by Django 4.2 on 2024-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0018_remove_webinarenrollment_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarenrollment',
            name='email',
        ),
        migrations.AddField(
            model_name='webinarenrollment',
            name='whatsapp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
