# Generated by Django 4.2 on 2024-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0019_remove_webinarenrollment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarenrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
