# Generated by Django 4.2 on 2024-11-27 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formation', '0020_alter_webinarenrollment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webinarenrollment',
            unique_together={('webinarId', 'user')},
        ),
    ]
