# Generated by Django 4.2 on 2024-12-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0021_alter_webinarenrollment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(default='', max_length=800)),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre')),
            ],
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='sous_titre',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_video', models.TextField(max_length=800)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.section')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_audio', models.TextField(max_length=800)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.section')),
            ],
        ),
        migrations.AddField(
            model_name='contenu',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
    ]
