# Generated by Django 4.2 on 2024-12-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0022_section_remove_contenu_chapitre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='nom_audio',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='audio',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.cours'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='titre',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='description',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom_cours',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='module',
            name='domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.domaine'),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom_module',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='section',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
    ]
