# Generated by Django 4.2 on 2024-12-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0023_alter_audio_nom_audio_alter_audio_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='nom_section',
            field=models.CharField(default='', max_length=80000),
        ),
    ]
