# Generated by Django 4.2 on 2024-12-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0024_alter_section_nom_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='nom_section',
            field=models.CharField(default='', max_length=15000),
        ),
    ]
