# Generated by Django 4.2 on 2024-12-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0030_alter_section_nom_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='chapitre',
        ),
    ]
