# Generated by Django 4.2 on 2024-12-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0032_alter_section_nom_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='chapitres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre'),
        ),
    ]
