# Generated by Django 4.2 on 2024-12-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0033_section_chapitres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='chapitres',
            new_name='chapitre',
        ),
    ]
